name: motivego
description: Desktop-first goals & stats with AI helper
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:           # ⬅️ ДОБАВЬ ЭТО
    sdk: flutter
  intl: ^0.20.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
  fl_chart: ^0.65.0
  path_provider: ^2.1.3
  share_plus: ^10.0.2
  file_picker: ^8.0.6
  lottie: ^3.1.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_ru.arb
  output-localization-file: app_localizations.dart
  output-dir: lib/l10n
