// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzCQTSo5GGVA8cje26xpftezrQqRd2F3Q',
    appId: '1:474815857049:android:e914d5d70f713bc5e35308',
    messagingSenderId: '474815857049',
    projectId: 'motiva-app-ru',
    storageBucket: 'motiva-app-ru.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjghZCTgp1VKwgdvXTvjuoaPPMrkFNDu4',
    appId: '1:474815857049:ios:d896ca3c7ccf1955e35308',
    messagingSenderId: '474815857049',
    projectId: 'motiva-app-ru',
    storageBucket: 'motiva-app-ru.firebasestorage.app',
    iosBundleId: 'com.example.motiva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeap2OeDlQvDDmhwIRD79tn71c3Hgqm00',
    appId: '1:474815857049:web:6311eeb395c8e859e35308',
    messagingSenderId: '474815857049',
    projectId: 'motiva-app-ru',
    authDomain: 'motiva-app-ru.firebaseapp.com',
    storageBucket: 'motiva-app-ru.firebasestorage.app',
    measurementId: 'G-86H8NG263N',
  );
}
